name: Lint

on:
  workflow_run:
    # workflows: [Test]
    types: 
      - completed

env:
  GO_VERSION: '1.24'
  GOLANGCI_LINT_VERSION: 'v2.1'

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
